Repository theia-ide/theia-apps, pull requests merged in 2019-11, with the labels that each got.

#258 Add 'cpp-debug' dependency
  theia-cpp-docker/README.md
  theia-cpp-docker/latest.package.json
  theia-cpp-docker/next.package.json
  theia-cpp-electron/README.md
  theia-cpp-electron/package.json
Labels: cpp, enhancement

#268 Add support for dark theme on macOS
  theia-electron/electron-builder.yml
Labels: electron, enhancement

#243 https and token authentication for theia-ide
  .travis.yml
  build_container.sh
  tests/package.json
  tests/wdio.theia-https.conf.js
  theia-https-docker/Dockerfile
  theia-https-docker/README.md
  theia-https-docker/ssl_theia.sh
  theia-https-docker/theiahere
Labels: enhancement, no-stale, security

#272 Fix JSON language server features
  .editorconfig
  .theia/settings.json
  .vscode/extensions.json
  .vscode/settings.json
  theia-cpp-docker/latest.package.json
  theia-cpp-docker/next.package.json
  theia-cpp-electron/package.json
  theia-dart-docker/latest.package.json
  theia-dart-docker/next.package.json
  theia-deb-build-docker/package.json
  theia-docker/latest.package.json
  theia-docker/next.package.json
  theia-electron/package.json
  theia-full-docker/latest.package.json
  theia-full-docker/next.package.json
  theia-go-docker/latest.package.json
  theia-go-docker/next.package.json
  theia-java-docker/latest.package.json
  theia-java-docker/next.package.json
  theia-python-docker/latest.package.json
  theia-python-docker/next.package.json
  theia-rpm-build-docker/package.json
  theia-ruby-docker/latest.package.json
  theia-rust-docker/next.package.json
  theia-swift-docker/latest.package.json
  theia-swift-docker/next.package.json
  yangster-docker/latest.package.json
  yangster-docker/next.package.json
Labels: bug

#276 [CI] add 'eclint' to lint and verify code base for conformity to '.editorconfig' rules
  .editorconfig
  .gitignore
  .travis.yml
  tests/package.json
  tests/tsconfig.json
  theia-cpp-docker/latest.package.json
  theia-cpp-docker/settings.json
  theia-cpp-electron/package.json
  theia-dart-docker/Dockerfile
  theia-dart-docker/latest.package.json
  theia-dart-docker/next.package.json
  theia-electron/README.md
  theia-electron/resources/.editorconfig
  theia-go-docker/Dockerfile
  theia-https-docker/README.md
  theia-openshift-docker/Dockerfile
  theia-ruby-docker/next.package.json
  theia-rust-docker/ex_bash
  theia-rust-docker/example_workspace/.theia/launch.json
  theia-rust-docker/example_workspace/adder/src/main.rs
  theia-rust-docker/install_node.sh
  theia-rust-docker/makefile
Labels: quality
